language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-imaging
  - git clone https://github.com/potentialventures/cocotb.git
  - export COCOTB=$PWD/cocotb
  - wget https://github.com/chiggs/travis_experiment/releases/download/v0.1.pre/modelsim_reduced.tgz
  - tar -xzf modelsim_reduced.tgz
  - export PATH=$PWD/modelsim_reduced/bin:$PATH
  - git clone https://github.com/chiggs/oc_jpegencode
script:
  - cd oc_jpegencode/tb && PYTHONPATH=/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages make SIM=modelsim

