language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6-dev-i386 lib32stdc++6 g++-multilib libxft2:i386 libxext6:i386 libncurses5:i386 libc6:i386 zlib1g:i386 libreadline6:i386 lib32z1
  - wget https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
  - tar -zxf Python-2.7.9.tgz
  - cd Python-2.7.9 && OPT=-m32 CFLAGS=-m32 LDFLAGS=-m32 ./configure --prefix=/tmp/python-2.7.9/i686 --disable-ipv6 --enable-shared
  - make -s -j 2
  - make install
  - cd
  - git clone https://github.com/potentialventures/cocotb.git
  - export COCOTB=$PWD/cocotb
  - wget https://github.com/chiggs/travis_experiment/releases/download/v0.2.pre/modelsim_reduced.tgz
  - tar -xzf modelsim_reduced.tgz
  - export PATH=$PWD/modelsim_reduced/bin:$PATH
#  - git clone https://github.com/chiggs/oc_jpegencode
script:
  - cd cocotb/examples/endian_swapper/tests && PATH=/tmp/python-2.7.9/i686/bin:$PATH LD_LIBRARY_PATH=/tmp/python-2.7.9/i686/lib make SIM=modelsim
#  - cd oc_jpegencode/tb && PATH=/tmp/python-2.7.9/i686/bin:$PATH LD_LIBRARY_PATH=/tmp/python-2.7.9/i686/lib make SIM=modelsim

